/** @type {import('cz-git').UserConfig} */
module.exports = {
  alias: { fd: 'docs: fix typos' },
  messages: {
    type: 'Selecciona el tipo de cambio que estás realizando:',
    scope: 'Indica el alcance (scope) de este cambio (opcional):',
    customScope: 'Indica el nombre del módulo o alcance personalizado:',
    subject: 'Escribe una descripción corta e imperativa del cambio (en ESPAÑOL):',
    body: 'Proporciona una descripción detallada del cambio (en ESPAÑOL) (usa "|" para saltos de línea) (opcional):\n',
    breaking: 'Listar cualquier CAMBIO DISRUPTIVO (Breaking Changes) (en ESPAÑOL) (opcional):\n',
    footerPrefixesSelect: 'Selecciona el tipo de issue o tarea vinculada (opcional):',
    customFooterPrefix: 'Introduce el prefijo del issue (ej. ARCH-, DEV-, TASK-):',
    footer: 'Introduce el número o ID del issue (ej. #42) (opcional):\n',
    confirmCommit: '¿Estás seguro de que deseas ejecutar el commit con los datos anteriores?'
  },
  types: [
    { value: 'feat', name: 'feat:     ✨  Una nueva funcionalidad o característica' },
    { value: 'fix', name: 'fix:      🐛  Una corrección de error o bug' },
    { value: 'docs', name: 'docs:     📚  Cambios únicamente en la documentación' },
    { value: 'style', name: 'style:    💄  Cambios que no afectan el significado del código (espacios, formato, etc.)' },
    { value: 'refactor', name: 'refactor: ♻️   Reestructuración de código que no corrige errores ni añade características' },
    { value: 'perf', name: 'perf:     ⚡️  Cambio de código para mejorar el rendimiento' },
    { value: 'test', name: 'test:     ✅  Añadir o corregir pruebas existentes' },
    { value: 'build', name: 'build:    📦  Cambios en el sistema de construcción o dependencias externas' },
    { value: 'ci', name: 'ci:       🎡  Cambios en los archivos de configuración y scripts de CI' },
    { value: 'chore', name: 'chore:    🔨  Otros cambios que no modifican código fuente o pruebas' },
    { value: 'revert', name: 'revert:   ⏪️  Revertir un commit previo' }
  ],
  useEmoji: true,
  emojiTrigger: ':',
  themeColorCode: '',
  scopes: [
    'setup',
    'auth',
    'database',
    'bimoneda',
    'cards',
    'simulator',
    'ui',
    'pwa',
    'config'
  ],
  enableMultipleScopes: false,
  scopeEnumSeparator: ',',
  allowCustomScopes: true,
  allowEmptyScopes: true,
  customScopesAlign: 'bottom',
  customScopesAlias: 'custom -> escribir scope personalizado',
  emptyScopesAlias: 'skip -> omitir scope',
  upperCaseSubject: false,
  markBreakingChangeMode: false,
  allowBreakingChanges: ['feat', 'fix'],
  breaklineNumber: 100,
  breaklineChar: '|',
  skipQuestions: [],
  issuePrefixes: [
    { value: 'ARCH-', name: 'ARCH-:  Tareas de arquitectura e infraestructura' },
    { value: 'DEV-', name: 'DEV-:   Tareas de desarrollo general' },
    { value: 'TASK-', name: 'TASK-:  Tareas y requerimientos funcionales' }
  ],
  customIssuePrefixAlign: 'top',
  emptyIssuePrefixAlias: 'skip -> omitir prefijo de issue',
  customIssuePrefixAlias: 'custom -> escribir prefijo personalizado',
  allowCustomIssuePrefix: true,
  allowEmptyIssuePrefix: true,
  confirmColorCode: '36',
  maxHeaderLength: 100,
  maxSubjectLength: Infinity,
  minSubjectLength: 0,
  scopeOverrides: undefined,
  defaultBody: '',
  defaultIssues: '',
  defaultScope: '',
  defaultSubject: ''
};
